this_is_a_map 'yes' 	

data_file 'DLC_ITYP_REQUEST' 'stream/akinaD.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Caline.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/DeriphillRemastered.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/DriftNoodle.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/EbisuTouge.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/EbisuWest.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/FujiShort.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/gokart.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/harugaharav2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Maxdrift.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/meihanc.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Minami.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Raceland.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/SekiaHills.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/SwiftySwamps.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tsuchi.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/myogi.ytyp'